# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Bit < Formula
  desc "A modern git CLI"
  homepage "https://github.com/chriswalz/bit"
  version "0.6.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chriswalz/bit/releases/v0.6.5/bit_0.6.5_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "2cd398486fa9f8808899d7411c2e0b1328432a5ce54b416ea357e803a14f5e48"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chriswalz/bit/releases/v0.6.5/bit_0.6.5_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "056f179220d90b34033ffc1cce081ace1ea3d1d6af31e5bcd9eff84b3005a724"
    end
  end
  
  depends_on "git"

  def install
    bin.install "bit"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/program --version"
    ...
  end
end
