package cmd

import "github.com/chriswalz/complete/v2"

var c = &complete.Command{Description: "",
	Sub: map[string]*complete.Command{
		"pack-refs":     {Description: "", Sub: map[string]*complete.Command{}},
		"revert":        {Description: "", Sub: map[string]*complete.Command{}},
		"squash":        {Description: "", Sub: map[string]*complete.Command{}},
		"diff-index":    {Description: "", Sub: map[string]*complete.Command{}},
		"flog":          {Description: "", Sub: map[string]*complete.Command{}},
		"http-backend":  {Description: "", Sub: map[string]*complete.Command{}},
		"verify-commit": {Description: "", Sub: map[string]*complete.Command{}},
		"br":            {Description: "", Sub: map[string]*complete.Command{}},
		"mv":            {Description: "", Sub: map[string]*complete.Command{}},
		"rev-parse":     {Description: "", Sub: map[string]*complete.Command{}},
		"worktree": {Description: "", Sub: map[string]*complete.Command{"unlock": {Description: "", Sub: map[string]*complete.Command{}},
			"add":    {Description: "", Sub: map[string]*complete.Command{}},
			"list":   {Description: "", Sub: map[string]*complete.Command{}},
			"lock":   {Description: "", Sub: map[string]*complete.Command{}},
			"move":   {Description: "", Sub: map[string]*complete.Command{}},
			"prune":  {Description: "", Sub: map[string]*complete.Command{}},
			"remove": {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"":          {Description: "", Sub: map[string]*complete.Command{}},
		"read-tree": {Description: "", Sub: map[string]*complete.Command{}},
		"svn": {Description: "", Sub: map[string]*complete.Command{"propset": {Description: "", Sub: map[string]*complete.Command{}},
			"set-tree":       {Description: "", Sub: map[string]*complete.Command{}},
			"gc":             {Description: "", Sub: map[string]*complete.Command{}},
			"info":           {Description: "", Sub: map[string]*complete.Command{}},
			"log":            {Description: "", Sub: map[string]*complete.Command{}},
			"propget":        {Description: "", Sub: map[string]*complete.Command{}},
			"proplist":       {Description: "", Sub: map[string]*complete.Command{}},
			"fetch":          {Description: "", Sub: map[string]*complete.Command{}},
			"init":           {Description: "", Sub: map[string]*complete.Command{}},
			"mkdirs":         {Description: "", Sub: map[string]*complete.Command{}},
			"blame":          {Description: "", Sub: map[string]*complete.Command{}},
			"branch":         {Description: "", Sub: map[string]*complete.Command{}},
			"clone":          {Description: "", Sub: map[string]*complete.Command{}},
			"create-ignore":  {Description: "", Sub: map[string]*complete.Command{}},
			"dcommit":        {Description: "", Sub: map[string]*complete.Command{}},
			"commit-diff":    {Description: "", Sub: map[string]*complete.Command{}},
			"find-rev":       {Description: "", Sub: map[string]*complete.Command{}},
			"migrate":        {Description: "", Sub: map[string]*complete.Command{}},
			"rebase":         {Description: "", Sub: map[string]*complete.Command{}},
			"reset":          {Description: "", Sub: map[string]*complete.Command{}},
			"show-externals": {Description: "", Sub: map[string]*complete.Command{}},
			"show-ignore":    {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"tag": {Description: "", Sub: map[string]*complete.Command{}},
		"bundle": {Description: "", Sub: map[string]*complete.Command{"create": {Description: "", Sub: map[string]*complete.Command{}},
			"list-heads": {Description: "", Sub: map[string]*complete.Command{}},
			"unbundle":   {Description: "", Sub: map[string]*complete.Command{}},
			"verify":     {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"get-tar-commit-id": {Description: "", Sub: map[string]*complete.Command{}},
		"prune":             {Description: "", Sub: map[string]*complete.Command{}},
		"quiltimport":       {Description: "", Sub: map[string]*complete.Command{}},
		"rm":                {Description: "", Sub: map[string]*complete.Command{}},
		"check-ignore":      {Description: "", Sub: map[string]*complete.Command{}},
		"cvsexportcommit":   {Description: "", Sub: map[string]*complete.Command{}},
		"diff":              {Description: "", Sub: map[string]*complete.Command{}},
		"write-tree":        {Description: "", Sub: map[string]*complete.Command{}},
		"gui": {Description: "", Sub: map[string]*complete.Command{"version": {Description: "", Sub: map[string]*complete.Command{}},
			"blame":   {Description: "", Sub: map[string]*complete.Command{}},
			"browser": {Description: "", Sub: map[string]*complete.Command{}},
			"citool":  {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"mailinfo": {Description: "", Sub: map[string]*complete.Command{}},
		"remote": {Description: "", Sub: map[string]*complete.Command{"set-head": {Description: "", Sub: map[string]*complete.Command{}},
			"update":       {Description: "", Sub: map[string]*complete.Command{}},
			"add":          {Description: "", Sub: map[string]*complete.Command{}},
			"prune":        {Description: "", Sub: map[string]*complete.Command{}},
			"set-branches": {Description: "", Sub: map[string]*complete.Command{}},
			"set-url":      {Description: "", Sub: map[string]*complete.Command{}},
			"show":         {Description: "", Sub: map[string]*complete.Command{}},
			"get-url":      {Description: "", Sub: map[string]*complete.Command{}},
			"remove":       {Description: "", Sub: map[string]*complete.Command{}},
			"rename":       {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"blame":         {Description: "", Sub: map[string]*complete.Command{}},
		"cherry-pick":   {Description: "", Sub: map[string]*complete.Command{}},
		"cvsimport":     {Description: "", Sub: map[string]*complete.Command{}},
		"symbolic-ref":  {Description: "", Sub: map[string]*complete.Command{}},
		"branch":        {Description: "", Sub: map[string]*complete.Command{}},
		"citool":        {Description: "", Sub: map[string]*complete.Command{}},
		"filter-branch": {Description: "", Sub: map[string]*complete.Command{}},
		"instaweb": {Description: "", Sub: map[string]*complete.Command{"restart": {Description: "", Sub: map[string]*complete.Command{}},
			"start": {Description: "", Sub: map[string]*complete.Command{}},
			"stop":  {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"di":                 {Description: "", Sub: map[string]*complete.Command{}},
		"fast-import":        {Description: "", Sub: map[string]*complete.Command{}},
		"hash-object":        {Description: "", Sub: map[string]*complete.Command{}},
		"index-pack":         {Description: "", Sub: map[string]*complete.Command{}},
		"range-diff":         {Description: "", Sub: map[string]*complete.Command{}},
		"commit":             {Description: "", Sub: map[string]*complete.Command{}},
		"count-objects":      {Description: "", Sub: map[string]*complete.Command{}},
		"describe":           {Description: "", Sub: map[string]*complete.Command{}},
		"send-email":         {Description: "", Sub: map[string]*complete.Command{}},
		"imap-send":          {Description: "", Sub: map[string]*complete.Command{}},
		"merge-file":         {Description: "", Sub: map[string]*complete.Command{}},
		"mktag":              {Description: "", Sub: map[string]*complete.Command{}},
		"patch-id":           {Description: "", Sub: map[string]*complete.Command{}},
		"rebase":             {Description: "", Sub: map[string]*complete.Command{}},
		"verify-tag":         {Description: "", Sub: map[string]*complete.Command{}},
		"clean":              {Description: "", Sub: map[string]*complete.Command{}},
		"daemon":             {Description: "", Sub: map[string]*complete.Command{}},
		"gst":                {Description: "", Sub: map[string]*complete.Command{}},
		"show-index":         {Description: "", Sub: map[string]*complete.Command{}},
		"gc":                 {Description: "", Sub: map[string]*complete.Command{}},
		"lola":               {Description: "", Sub: map[string]*complete.Command{}},
		"rev-list":           {Description: "", Sub: map[string]*complete.Command{}},
		"http-fetch":         {Description: "", Sub: map[string]*complete.Command{}},
		"ls-tree":            {Description: "", Sub: map[string]*complete.Command{}},
		"update-ref":         {Description: "", Sub: map[string]*complete.Command{}},
		"check-mailmapstdin": {Description: "", Sub: map[string]*complete.Command{}},
		"co":                 {Description: "", Sub: map[string]*complete.Command{}},
		"for-each-ref":       {Description: "", Sub: map[string]*complete.Command{}},
		"apply":              {Description: "", Sub: map[string]*complete.Command{}},
		"lg":                 {Description: "", Sub: map[string]*complete.Command{}},
		"show-branch":        {Description: "", Sub: map[string]*complete.Command{}},
		"ds":                 {Description: "", Sub: map[string]*complete.Command{}},
		"zsh: do you wish to see all 157 possibilities (152 lines)?": {Description: "", Sub: map[string]*complete.Command{}},
		"name-rev":       {Description: "", Sub: map[string]*complete.Command{}},
		"update-index":   {Description: "", Sub: map[string]*complete.Command{}},
		"upload-archive": {Description: "", Sub: map[string]*complete.Command{}},
		"grep":           {Description: "", Sub: map[string]*complete.Command{}},
		"ls-files":       {Description: "", Sub: map[string]*complete.Command{}},
		"mktree":         {Description: "", Sub: map[string]*complete.Command{}},
		"reset":          {Description: "", Sub: map[string]*complete.Command{}},
		"sta": {Description: "", Sub: map[string]*complete.Command{"apply": {Description: "", Sub: map[string]*complete.Command{}},
			"show":   {Description: "", Sub: map[string]*complete.Command{}},
			"branch": {Description: "", Sub: map[string]*complete.Command{}},
			"clear":  {Description: "", Sub: map[string]*complete.Command{}},
			"create": {Description: "", Sub: map[string]*complete.Command{}},
			"drop":   {Description: "", Sub: map[string]*complete.Command{}},
			"list":   {Description: "", Sub: map[string]*complete.Command{}},
			"pop":    {Description: "", Sub: map[string]*complete.Command{}},
			"save":   {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"bisect": {Description: "", Sub: map[string]*complete.Command{"bad": {Description: "", Sub: map[string]*complete.Command{}},
			"terms":     {Description: "", Sub: map[string]*complete.Command{}},
			"visualize": {Description: "", Sub: map[string]*complete.Command{}},
			"next":      {Description: "", Sub: map[string]*complete.Command{}},
			"replay":    {Description: "", Sub: map[string]*complete.Command{}},
			"reset":     {Description: "", Sub: map[string]*complete.Command{}},
			"run":       {Description: "", Sub: map[string]*complete.Command{}},
			"skip":      {Description: "", Sub: map[string]*complete.Command{}},
			"good":      {Description: "", Sub: map[string]*complete.Command{}},
			"help":      {Description: "", Sub: map[string]*complete.Command{}},
			"log":       {Description: "", Sub: map[string]*complete.Command{}},
			"start":     {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"checkout-index": {Description: "", Sub: map[string]*complete.Command{}},
		"diff-files":     {Description: "", Sub: map[string]*complete.Command{}},
		"show":           {Description: "", Sub: map[string]*complete.Command{}},
		"rerere": {Description: "", Sub: map[string]*complete.Command{"clear": {Description: "", Sub: map[string]*complete.Command{}},
			"diff":      {Description: "", Sub: map[string]*complete.Command{}},
			"forget":    {Description: "", Sub: map[string]*complete.Command{}},
			"gc":        {Description: "", Sub: map[string]*complete.Command{}},
			"remaining": {Description: "", Sub: map[string]*complete.Command{}},
			"status":    {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"unstage":            {Description: "", Sub: map[string]*complete.Command{}},
		"var GIT_":           {Description: "", Sub: map[string]*complete.Command{}},
		"format-patch":       {Description: "", Sub: map[string]*complete.Command{}},
		"interpret-trailers": {Description: "", Sub: map[string]*complete.Command{}},
		"merge-tree":         {Description: "", Sub: map[string]*complete.Command{}},
		"st":                 {Description: "", Sub: map[string]*complete.Command{}},
		"cvsserver":          {Description: "", Sub: map[string]*complete.Command{}},
		"http-push": {Description: "", Sub: map[string]*complete.Command{"file:": {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"notes": {Description: "", Sub: map[string]*complete.Command{"add": {Description: "", Sub: map[string]*complete.Command{}},
			"append":  {Description: "", Sub: map[string]*complete.Command{}},
			"get-ref": {Description: "", Sub: map[string]*complete.Command{}},
			"remove":  {Description: "", Sub: map[string]*complete.Command{}},
			"show":    {Description: "", Sub: map[string]*complete.Command{}},
			"copy":    {Description: "", Sub: map[string]*complete.Command{}},
			"edit":    {Description: "", Sub: map[string]*complete.Command{}},
			"list":    {Description: "", Sub: map[string]*complete.Command{}},
			"merge":   {Description: "", Sub: map[string]*complete.Command{}},
			"prune":   {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"prune-packed":       {Description: "", Sub: map[string]*complete.Command{}},
		"request-pull":       {Description: "", Sub: map[string]*complete.Command{}},
		"unpack-file":        {Description: "", Sub: map[string]*complete.Command{}},
		"difftool":           {Description: "", Sub: map[string]*complete.Command{}},
		"llog":               {Description: "", Sub: map[string]*complete.Command{}},
		"mergetool":          {Description: "", Sub: map[string]*complete.Command{}},
		"parse-remote":       {Description: "", Sub: map[string]*complete.Command{}},
		"receive-pack":       {Description: "", Sub: map[string]*complete.Command{}},
		"stripspace":         {Description: "", Sub: map[string]*complete.Command{}},
		"check-ref-format":   {Description: "", Sub: map[string]*complete.Command{}},
		"fsck":               {Description: "", Sub: map[string]*complete.Command{}},
		"merge-one-file":     {Description: "", Sub: map[string]*complete.Command{}},
		"pack-redundant":     {Description: "", Sub: map[string]*complete.Command{}},
		"show-ref":           {Description: "", Sub: map[string]*complete.Command{}},
		"verify-pack":        {Description: "", Sub: map[string]*complete.Command{}},
		"checkout":           {Description: "", Sub: map[string]*complete.Command{}},
		"fmt-merge-msg":      {Description: "", Sub: map[string]*complete.Command{}},
		"merge":              {Description: "", Sub: map[string]*complete.Command{}},
		"archimport":         {Description: "", Sub: map[string]*complete.Command{}},
		"blog":               {Description: "", Sub: map[string]*complete.Command{}},
		"mailsplit":          {Description: "", Sub: map[string]*complete.Command{}},
		"merge-base":         {Description: "", Sub: map[string]*complete.Command{}},
		"pack-objects":       {Description: "", Sub: map[string]*complete.Command{}},
		"update-server-info": {Description: "", Sub: map[string]*complete.Command{}},
		"zsh: do you wish to see all 150 possibilities (150 lines)?": {Description: "", Sub: map[string]*complete.Command{}},
		"add":         {Description: "", Sub: map[string]*complete.Command{}},
		"cherry":      {Description: "", Sub: map[string]*complete.Command{}},
		"fast-export": {Description: "", Sub: map[string]*complete.Command{}},
		"merge-index": {Description: "", Sub: map[string]*complete.Command{}},
		"archive":     {Description: "", Sub: map[string]*complete.Command{}},
		"check-attr": {Description: "", Sub: map[string]*complete.Command{"ident": {Description: "", Sub: map[string]*complete.Command{}},
			"merge":  {Description: "", Sub: map[string]*complete.Command{}},
			"crlf":   {Description: "", Sub: map[string]*complete.Command{}},
			"diff":   {Description: "", Sub: map[string]*complete.Command{}},
			"filter": {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"cp":      {Description: "", Sub: map[string]*complete.Command{}},
		"fixup":   {Description: "", Sub: map[string]*complete.Command{}},
		"log":     {Description: "", Sub: map[string]*complete.Command{}},
		"lol":     {Description: "", Sub: map[string]*complete.Command{}},
		"replace": {Description: "", Sub: map[string]*complete.Command{}},
		"rum":     {Description: "", Sub: map[string]*complete.Command{}},
		"cat-file": {Description: "", Sub: map[string]*complete.Command{"blob": {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"ci":             {Description: "", Sub: map[string]*complete.Command{}},
		"commit-tree":    {Description: "", Sub: map[string]*complete.Command{}},
		"unpack-objects": {Description: "", Sub: map[string]*complete.Command{}},
		"whatchanged":    {Description: "", Sub: map[string]*complete.Command{}},
		"am":             {Description: "", Sub: map[string]*complete.Command{}},
		"shortlog":       {Description: "", Sub: map[string]*complete.Command{}},
		"shell":          {Description: "", Sub: map[string]*complete.Command{}},
		"submodule": {Description: "", Sub: map[string]*complete.Command{"update": {Description: "", Sub: map[string]*complete.Command{}},
			"status":        {Description: "", Sub: map[string]*complete.Command{}},
			"sync":          {Description: "", Sub: map[string]*complete.Command{}},
			"deinit":        {Description: "", Sub: map[string]*complete.Command{}},
			"foreach":       {Description: "", Sub: map[string]*complete.Command{}},
			"init":          {Description: "", Sub: map[string]*complete.Command{}},
			"summary":       {Description: "", Sub: map[string]*complete.Command{}},
			"absorbgitdirs": {Description: "", Sub: map[string]*complete.Command{}},
			"add":           {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"reflog": {Description: "", Sub: map[string]*complete.Command{"delete": {Description: "", Sub: map[string]*complete.Command{}},
			"exists": {Description: "", Sub: map[string]*complete.Command{}},
			"expire": {Description: "", Sub: map[string]*complete.Command{}},
			"show":   {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"repack":      {Description: "", Sub: map[string]*complete.Command{}},
		"upload-pack": {Description: "", Sub: map[string]*complete.Command{}},
		"status":      {Description: "", Sub: map[string]*complete.Command{}},
		"subtree": {Description: "", Sub: map[string]*complete.Command{"push": {Description: "", Sub: map[string]*complete.Command{}},
			"split": {Description: "", Sub: map[string]*complete.Command{}},
			"add":   {Description: "", Sub: map[string]*complete.Command{}},
			"merge": {Description: "", Sub: map[string]*complete.Command{}},
			"pull":  {Description: "", Sub: map[string]*complete.Command{}},
		}},
		"diff-tree": {Description: "", Sub: map[string]*complete.Command{}},
		"init":      {Description: "", Sub: map[string]*complete.Command{}},
		"stash": {Description: "", Sub: map[string]*complete.Command{"drop": {Description: "", Sub: map[string]*complete.Command{}},
			"list":   {Description: "", Sub: map[string]*complete.Command{}},
			"show":   {Description: "", Sub: map[string]*complete.Command{}},
			"apply":  {Description: "", Sub: map[string]*complete.Command{}},
			"branch": {Description: "", Sub: map[string]*complete.Command{}},
			"clear":  {Description: "", Sub: map[string]*complete.Command{}},
			"create": {Description: "", Sub: map[string]*complete.Command{}},
			"pop":    {Description: "", Sub: map[string]*complete.Command{}},
			"save":   {Description: "", Sub: map[string]*complete.Command{}},
		}},
	}}
